#! /bin/sh

if test -d fw/bin
  then
    PATH="`pwd`/fw/bin:$PATH"
    export PATH
  fi

fwb=`which fw-bootstrap`

if test -z "$fwb"
  then
    echo "bootstrap: fatal: fw-bootstrap not installed or not in PATH" 1>&2
    exit 1
  fi

"$fwb" --fw_version "0.1.32" --name osmos --template erlang --revision svn --svn_project_path https://osmos.googlecode.com/svn/trunk/osmos --svn_tag_root https://osmos.googlecode.com/svn/tags/osmos/ "$@"
